export const Skills = Object.freeze({
    backend: ['Node.js', 'Express.js', 'Drizzle ORM', 'Python', 'Go'],
    frontend: [
        'React',
        'Solid.js',
        'Vue.js',
        'TypeScript',
        'JavaScript',
        'Tailwind',
        'HTML5',
        'CSS3',
    ],
    databases: ['MySQL', 'PostgreSQL', 'MongoDB', 'Redis'],
    other: [
        'Git',
        'Figma',
        'Socket.io',
        'Zod',
        'Vite',
        'Cloudflare',
        'Digital Ocean',
        'Heroku',
        'Bash Script',
    ],
});
